# Generated by Django 4.1 on 2023-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_delete_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='reg_no',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='room_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
